FSpacer/Models/SpacerCard.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FSpacer.Models
{
    public class SpacerCard
    {
        public int ID { get; set; }
        public Int32 HorizontalGearCaseDeviation { get; set; }
        public Int32 HorizontalCarrierDeviation { get; set; }
        public Int32 Bearing { get; set; }
        public Single HMDGear { get; set; }
        public Int32 VerticalGearCaseDeviation { get; set; }
        public Int32 VerticalCarrierDeviation { get; set; }
        public Single GearMount { get; set; }
        public Single VMDGear { get; set; }
        public string DriveNumber { get; set; }
        public Int32 OperatorID { get; set; }
        public DateTime Date { get; set; }
        public bool Active { get; set; }
        public Single Backlash { get; set; }
        public Single HorizontalSetting { get; set; } = 0;
        public Single OutputSetting { get; set; } = 0;
        public string HelicalGearNumber { get; set; }
        public string HelicalPinionNumber { get; set; }
        public string HorizontalSpacerLength { get; set; }
        public string VerticalSpacerLength { get; set; }

        public static string GetHorizontalSpacerLength(int Model, int HorizontalGearCaseDeviation, int HorizontalCarrierDeviation, int Bearing, float HMDGear)
        {
            string HorizontalSpacerLength = "";

            return HorizontalSpacerLength;
        }


        public static string GetVerticalSpacerLength(int Model, int VerticalGearCaseDeviation, int VerticalCarrierDeviation, float VMDGear, float GearMount)
        {
            string VerticalSpacerLength = "";

            return VerticalSpacerLength;
        }
        
        public static int ModelToInt(string Model)
        {
            int Convert = 0;

            return Convert;
        }

        //public string Size { get; set; }
        //public string Ratio { get; set; }

        //public string GearNumber { get; set; }
        //public string IntermediateSetting { get; set; }



    }
}

FSpacer/Controllers/SpacerCardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FSpacer.Data;
using FSpacer.Models;

namespace FSpacer.Controllers
{
    public class SpacerCardsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SpacerCardsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SpacerCards
        public async Task<IActionResult> Index()
        {
            return View(await _context.SpacerCards.ToListAsync());
        }

        public IActionResult HomePage()
        {
            return View();
        }

        public IActionResult SearchSpacerCards()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SearchResults(SearchInputModel search)
        {

            var spacercards = await _context.SpacerCards.ToListAsync();

            var filtered = spacercards.Where(s => s.DriveNumber == search.SearchDriveNumber);

            return View(filtered);
        }

        // GET: SpacerCards/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spacerCard = await _context.SpacerCards
                .SingleOrDefaultAsync(m => m.ID == id);
            if (spacerCard == null)
            {
                return NotFound();
            }

            return View(spacerCard);
        }

        // GET: SpacerCards/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SpacerCards/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,HorizontalGearCaseDeviation,HorizontalCarrierDeviation,Bearing,HMDGear,VerticalGearCaseDeviation,VerticalCarrierDeviation,GearMount,VMDGear,DriveNumber,OperatorID,Date,Active,Backlash,HorizontalSetting,OutputSetting,HelicalGearNumber,HelicalPinionNumber,HorizontalSpacerLength,VerticalSpacerLength")] SpacerCard spacerCard)
        {
            if (ModelState.IsValid)
            {
                _context.Add(spacerCard);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(spacerCard);
        }

        // GET: SpacerCards/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spacerCard = await _context.SpacerCards.SingleOrDefaultAsync(m => m.ID == id);
            if (spacerCard == null)
            {
                return NotFound();
            }
            return View(spacerCard);
        }

        // POST: SpacerCards/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,HorizontalGearCaseDeviation,HorizontalCarrierDeviation,Bearing,HMDGear,VerticalGearCaseDeviation,VerticalCarrierDeviation,GearMount,VMDGear,DriveNumber,OperatorID,Date,Active,Backlash,HorizontalSetting,OutputSetting,HelicalGearNumber,HelicalPinionNumber,HorizontalSpacerLength,VerticalSpacerLength")] SpacerCard spacerCard)
        {
            if (id != spacerCard.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(spacerCard);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SpacerCardExists(spacerCard.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(spacerCard);
        }

        // GET: SpacerCards/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spacerCard = await _context.SpacerCards
                .SingleOrDefaultAsync(m => m.ID == id);
            if (spacerCard == null)
            {
                return NotFound();
            }

            return View(spacerCard);
        }

        // POST: SpacerCards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var spacerCard = await _context.SpacerCards.SingleOrDefaultAsync(m => m.ID == id);
            _context.SpacerCards.Remove(spacerCard);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SpacerCardExists(int id)
        {
            return _context.SpacerCards.Any(e => e.ID == id);
        }

        [HttpPost, ActionName("Update")]
        public IActionResult SpacerCardUpdate(SpacerCard sc)
        {

            //_context. 
            var test = sc.DriveNumber;

            _context.SaveChanges();
            return View("SpacerCardConfirmed");

        }
    }
}

FSpacer/Views/SpacerCards/Create.cshtml
@model FSpacer.Models.SpacerCard

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>SpacerCard</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="HorizontalGearCaseDeviation" class="control-label"></label>
                <input asp-for="HorizontalGearCaseDeviation" class="form-control" />
                <span asp-validation-for="HorizontalGearCaseDeviation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HorizontalCarrierDeviation" class="control-label"></label>
                <input asp-for="HorizontalCarrierDeviation" class="form-control" />
                <span asp-validation-for="HorizontalCarrierDeviation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bearing" class="control-label"></label>
                <input asp-for="Bearing" class="form-control" />
                <span asp-validation-for="Bearing" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HMDGear" class="control-label"></label>
                <input asp-for="HMDGear" class="form-control" />
                <span asp-validation-for="HMDGear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VerticalGearCaseDeviation" class="control-label"></label>
                <input asp-for="VerticalGearCaseDeviation" class="form-control" />
                <span asp-validation-for="VerticalGearCaseDeviation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VerticalCarrierDeviation" class="control-label"></label>
                <input asp-for="VerticalCarrierDeviation" class="form-control" />
                <span asp-validation-for="VerticalCarrierDeviation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GearMount" class="control-label"></label>
                <input asp-for="GearMount" class="form-control" />
                <span asp-validation-for="GearMount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VMDGear" class="control-label"></label>
                <input asp-for="VMDGear" class="form-control" />
                <span asp-validation-for="VMDGear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DriveNumber" class="control-label"></label>
                <input asp-for="DriveNumber" class="form-control" />
                <span asp-validation-for="DriveNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OperatorID" class="control-label"></label>
                <input asp-for="OperatorID" class="form-control" />
                <span asp-validation-for="OperatorID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Backlash" class="control-label"></label>
                <input asp-for="Backlash" class="form-control" />
                <span asp-validation-for="Backlash" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HorizontalSetting" class="control-label"></label>
                <input asp-for="HorizontalSetting" class="form-control" />
                <span asp-validation-for="HorizontalSetting" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OutputSetting" class="control-label"></label>
                <input asp-for="OutputSetting" class="form-control" />
                <span asp-validation-for="OutputSetting" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HelicalGearNumber" class="control-label"></label>
                <input asp-for="HelicalGearNumber" class="form-control" />
                <span asp-validation-for="HelicalGearNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HelicalPinionNumber" class="control-label"></label>
                <input asp-for="HelicalPinionNumber" class="form-control" />
                <span asp-validation-for="HelicalPinionNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HorizontalSpacerLength" class="control-label"></label>
                <input asp-for="HorizontalSpacerLength" class="form-control" />
                <span asp-validation-for="HorizontalSpacerLength" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VerticalSpacerLength" class="control-label"></label>
                <input asp-for="VerticalSpacerLength" class="form-control" />
                <span asp-validation-for="VerticalSpacerLength" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FSpacer/Views/SpacerCards/Delete.cshtml
@model FSpacer.Models.SpacerCard

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SpacerCard</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HorizontalGearCaseDeviation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HorizontalGearCaseDeviation)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HorizontalCarrierDeviation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HorizontalCarrierDeviation)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Bearing)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Bearing)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HMDGear)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HMDGear)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VerticalGearCaseDeviation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VerticalGearCaseDeviation)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VerticalCarrierDeviation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VerticalCarrierDeviation)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GearMount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GearMount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VMDGear)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VMDGear)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DriveNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DriveNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OperatorID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OperatorID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Backlash)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Backlash)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HorizontalSetting)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HorizontalSetting)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OutputSetting)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OutputSetting)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HelicalGearNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HelicalGearNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HelicalPinionNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HelicalPinionNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HorizontalSpacerLength)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HorizontalSpacerLength)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VerticalSpacerLength)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VerticalSpacerLength)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FSpacer/Views/SpacerCards/Details.cshtml
@model FSpacer.Models.SpacerCard

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>SpacerCard</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HorizontalGearCaseDeviation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HorizontalGearCaseDeviation)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HorizontalCarrierDeviation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HorizontalCarrierDeviation)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Bearing)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Bearing)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HMDGear)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HMDGear)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VerticalGearCaseDeviation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VerticalGearCaseDeviation)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VerticalCarrierDeviation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VerticalCarrierDeviation)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GearMount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GearMount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VMDGear)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VMDGear)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DriveNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DriveNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OperatorID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OperatorID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Backlash)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Backlash)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HorizontalSetting)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HorizontalSetting)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OutputSetting)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OutputSetting)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HelicalGearNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HelicalGearNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HelicalPinionNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HelicalPinionNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HorizontalSpacerLength)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HorizontalSpacerLength)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VerticalSpacerLength)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VerticalSpacerLength)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FSpacer/Views/SpacerCards/Edit.cshtml
@model FSpacer.Models.SpacerCard

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>SpacerCard</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="HorizontalGearCaseDeviation" class="control-label"></label>
                <input asp-for="HorizontalGearCaseDeviation" class="form-control" />
                <span asp-validation-for="HorizontalGearCaseDeviation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HorizontalCarrierDeviation" class="control-label"></label>
                <input asp-for="HorizontalCarrierDeviation" class="form-control" />
                <span asp-validation-for="HorizontalCarrierDeviation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bearing" class="control-label"></label>
                <input asp-for="Bearing" class="form-control" />
                <span asp-validation-for="Bearing" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HMDGear" class="control-label"></label>
                <input asp-for="HMDGear" class="form-control" />
                <span asp-validation-for="HMDGear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VerticalGearCaseDeviation" class="control-label"></label>
                <input asp-for="VerticalGearCaseDeviation" class="form-control" />
                <span asp-validation-for="VerticalGearCaseDeviation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VerticalCarrierDeviation" class="control-label"></label>
                <input asp-for="VerticalCarrierDeviation" class="form-control" />
                <span asp-validation-for="VerticalCarrierDeviation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GearMount" class="control-label"></label>
                <input asp-for="GearMount" class="form-control" />
                <span asp-validation-for="GearMount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VMDGear" class="control-label"></label>
                <input asp-for="VMDGear" class="form-control" />
                <span asp-validation-for="VMDGear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DriveNumber" class="control-label"></label>
                <input asp-for="DriveNumber" class="form-control" />
                <span asp-validation-for="DriveNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OperatorID" class="control-label"></label>
                <input asp-for="OperatorID" class="form-control" />
                <span asp-validation-for="OperatorID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Backlash" class="control-label"></label>
                <input asp-for="Backlash" class="form-control" />
                <span asp-validation-for="Backlash" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HorizontalSetting" class="control-label"></label>
                <input asp-for="HorizontalSetting" class="form-control" />
                <span asp-validation-for="HorizontalSetting" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OutputSetting" class="control-label"></label>
                <input asp-for="OutputSetting" class="form-control" />
                <span asp-validation-for="OutputSetting" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HelicalGearNumber" class="control-label"></label>
                <input asp-for="HelicalGearNumber" class="form-control" />
                <span asp-validation-for="HelicalGearNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HelicalPinionNumber" class="control-label"></label>
                <input asp-for="HelicalPinionNumber" class="form-control" />
                <span asp-validation-for="HelicalPinionNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HorizontalSpacerLength" class="control-label"></label>
                <input asp-for="HorizontalSpacerLength" class="form-control" />
                <span asp-validation-for="HorizontalSpacerLength" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VerticalSpacerLength" class="control-label"></label>
                <input asp-for="VerticalSpacerLength" class="form-control" />
                <span asp-validation-for="VerticalSpacerLength" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FSpacer/Views/SpacerCards/HomePage.cshtml
@{
    ViewData["Title"] = "HomePage";
}

<h2>Welcome to the FSpacer Demo</h2>

<p>
    <a asp-action="Index">Go to the database.</a>
</p>

FSpacer/Views/SpacerCards/Index.cshtml
@model IEnumerable<FSpacer.Models.SpacerCard>

@{
    ViewData["Title"] = "Index";
}


<h2>FSpacer Data Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<p>
    <a asp-action="SearchSpacerCards">Search Via Drive Number</a>
</p>
<table class="table">
    <thead>
        <tr>

                <th>
                    @Html.DisplayNameFor(model => model.DriveNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OperatorID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Active)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DriveNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OperatorID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Active)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

FSpacer/Views/SpacerCards/SearchResults.cshtml
@model IEnumerable<FSpacer.Models.SpacerCard>

@{
    ViewData["Title"] = "SearchResults";
}

<h2>Searc hResults</h2>

@if (Model.Count() == 0)
{
    <p>No Drive Numbers matching those terms were found!</p>
}
else
{
    <p>The following Drive Numbers were found:</p>
    <ul>
        @foreach (var s in Model)
        {
            <li>@s.DriveNumber</li>
        }
    </ul>
}

FSpacer/Views/SpacerCards/SearchSpacerCards.cshtml
@model FSpacer.Models.SearchInputModel
@{
    ViewData["Title"] = "SearchSpacerCards";
}

<h2>Search Spacer Cards</h2>

<form asp-controller="SpacerCards" asp-action="SearchResults" method="post">
    <label asp-for="SearchDriveNumber"></label>
    <input asp-for="SearchDriveNumber" type="text" /><br />
    <input type="submit" value="submit" /><br />
</form>

FSpacer/Views/SpacerCards/SpacerCardConfirmed.cshtml
@{
    ViewData["Title"] = "SpacerCardConfirmed";
}

<h2>SpacerCardConfirmed</h2>

<h2>SaveComplete</h2>